clangdev:
  - 8.*
  - 9.*
  - 10.*
  - 11.*
  - 12.*
  - 13.*
  - 14.*
  - 15.*
  - 16.*
  - 17.*
  - 18.*
  - cling  #[linux]
zip_keys:
  -
    - clangdev

c_compiler:          # [osx]
  - clang_bootstrap  # [osx]
cxx_compiler:        # [osx]
  - clang_bootstrap  # [osx]

# Because of cling requiring gxx 10.
cxx_compiler_version:  # [linux]
  - 10                 # [linux]

c_stdlib_version:          # [osx and x86_64]
  - "10.13"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.13"                # [osx and x86_64]
