llvmdev:
#  - 7.*
  - 8.*
  - 9.*
  - 10.*
  - 11.*
  - 12.*
  - 13.*
  - 14.*
  - 15.*
  - 16.*
  - 17.*
clangdev:
#  - 7.*
  - 8.*
  - 9.*
  - 10.*
  - 11.*
  - 12.*
  - 13.*
  - 14.*
  - 15.*
  - 16.*
  - 17.*
zip_keys:
  -
    - llvmdev
    - clangdev

c_compiler:          # [osx]
  - clang_bootstrap  # [osx]
cxx_compiler:        # [osx]
  - clang_bootstrap  # [osx]

MACOSX_SDK_VERSION:  # [osx and x86_64]
  - 10.12            # [osx and x86_64]