llvmdev:
  - 7.*
  - 8.*
  - 9.*
  - 10.*
  - 11.*
  - 12.*
  - 13.*
  - 14.*
clangdev:
  - 7.*
  - 8.*
  - 9.*
  - 10.*
  - 11.*
  - 12.*
  - 13.*
  - 14.*
zip_keys:
  -
    - llvmdev
    - clangdev
