MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - "13.0"  # [osx and x86_64]
  - "14.0"  # [osx and x86_64]
#  - "14.0"  # [osx and arm64]
MACOSX_SDK_VERSION:  # [osx]
  - "13.0"  # [osx and x86_64]
  - "14.0"  # [osx and x86_64]
#  - "14.0"  # [osx and arm64]
llvmdev:
  - 7.*
  - 8.*
  - 9.*
  - 10.*
  - 11.*
  - 12.*
  - 13.*
  - 14.*
  - 15.*
  - 16.*
  - 17.*
clangdev:
  - 7.*
  - 8.*
  - 9.*
  - 10.*
  - 11.*
  - 12.*
  - 13.*
  - 14.*
  - 15.*
  - 16.*
  - 17.*
zip_keys:
  -
    - llvmdev
    - clangdev
