llvmdev:
  - 8.*
  - 9.*
  - 10.*
  - 11.*
  - 12.*
  - 13.*
  - 14.*
  - 15.*
  - 16.*
  - 17.*
  - 9.0.1.cling_v0.9
clangdev:
  - 8.*
  - 9.*
  - 10.*
  - 11.*
  - 12.*
  - 13.*
  - 14.*
  - 15.*
  - 16.*
  - 17.*
  - 9.0.1.cling_v0.9
zip_keys:
  -
    - llvmdev
    - clangdev

c_compiler:          # [osx]
  - clang_bootstrap  # [osx]
cxx_compiler:        # [osx]
  - clang_bootstrap  # [osx]

MACOSX_SDK_VERSION:  # [osx and x86_64]
  - 10.13            # [osx and x86_64]
