clangdev:
  - 11.*
  - 12.*
  - 13.*
  - 14.*
  - 15.*
  - 16.*
  - 17.*
  - 18.*
  - 19.*
  - 20.*
  - 21.*
zip_keys:
  -
    - clangdev

c_compiler:          # [osx]
  - clang_bootstrap  # [osx]
cxx_compiler:        # [osx]
  - clang_bootstrap  # [osx]

cxx_compiler_version:  # [linux]
  - 10                 # [linux]

c_stdlib:
  - macosx_deployment_target    # [osx]
c_stdlib_version:
  - 10.13                       # [osx]
