{% set name = "clad" %}
{% set version = "1.4" %}
{% set build_number = 1 %}

{% set clang_ver = (clangdev or "None").split(".")[0] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vgvassilev/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: da5584159499b05d77cfca40baee5d4d212beb269637736fee34d84d2b82d419
  folder: source

build:
  skip: true  # [win]
  skip: true  # [linux and (clangdev in ("7.*", "8.*"))]
  skip: true  # [osx and (clangdev in ("7.*", "8.*", "9.*", "10.*", "11.*", "12.*"))]
  number: {{ build_number }}
  string: clang{{ clang_ver }}_h{{ PKG_HASH }}_{{ build_number }}

requirements:
  build:
    - cmake
    - make   # [unix]
    - ninja  # [win]
    - {{ compiler('cxx') }}
    - sed    # [unix]
    # LLVM was split into multiple outputs as part of the 8.x update
    - llvm  # [llvmdev not in ("5.*", "6.*", "7.*")]
    - llvmdev
    - clangdev {{ clang_ver }}
    - libcxx {{ cxx_compiler_version }}  # [osx]
  host:
    - xz
    - zstd
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("13.0") }}  # [osx]
  run_constrained:
    - cling ==9999999999  # [clangdev != "13.*"]
    - cling 0.9           # [clangdev == "13.*"]
    - clangdev =={{ clang_ver }}

test:
  requires:   # [clangdev == "13.*" and not win]
    - jupyter_kernel_test  # [clangdev == "13.*" and not win]
    - xeus-cling          # [clangdev == "13.*" and not win]
  files:
    - $RECIPE_DIR/jupyter_Clad_kernel_test.py
  commands:
    - python $RECIPE_DIR/jupyter_Clad_kernel_test.py  # [clangdev == "5.*" and not win]
    - test -f $PREFIX/lib/clad${SHLIB_EXT}  # [unix]
    # - if not exist %LIBRARY_BIN%\\clad.dll exit 1  # [win]
    #- if not exist %LIBRARY_LIB%\\cladDifferentiator.lib exit 1  # [win]
    #- if not exist %LIBRARY_LIB%\\cladPlugin.lib exit 1  # [win]

about:
  home: https://github.com/vgvassilev/clad
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: source/License.txt
  summary: clad -- automatic differentiation for C/C++
  description: |
    Clad enables automatic differentiation (AD) for C++. It is based on LLVM
    compiler infrastructure and is a plugin for Clang compiler.
  doc_url: https://github.com/vgvassilev/clad/blob/master/README.md
  dev_url: https://github.com/vgvassilev/clad/wiki

extra:
  recipe-maintainers:
    - vgvassilev
    - alexander-penev
    - oshadura
