{% set name = "clad" %}
{% set version = "0.9" %}
{% set build_number = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vgvassilev/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0876cd1d00eb222f39b34b1db3dc5f9b873b7a26af01e98bf5fb1950670583d2
  folder: source

build:
  number: {{ build_number }}
  string: clang{{ (clangdev or "None").split(".")[0] }}_h{{ PKG_HASH }}_{{ build_number }}

requirements:
  build:
    - cmake
    - make  # [unix]
    - ninja  # [win]
    - {{ compiler('cxx') }}
  host:
    # LLVM was split into multiple outputs as part of the 8.x update
    - llvm  # [llvmdev not in ("5.*", "6.*", "7.*")]
    - llvmdev
    - clangdev
  run_constrained:
    - cling ==9999999999  # [clangdev != "5.*"]
    - cling 0.8           # [clangdev == "5.*"]

test:
  commands:
    - test -f $PREFIX/lib/clad${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libcladDifferentiator.a  # [unix]
    - test -f $PREFIX/lib/libcladPlugin.a  # [unix]
    # - if not exist %LIBRARY_BIN%\\clad.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\cladDifferentiator.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\cladPlugin.lib exit 1  # [win]

about:
  home: https://github.com/vgvassilev/clad
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: source/License.txt
  summary: clad -- automatic differentiation for C/C++
  description: |
    Clad enables automatic differentiation (AD) for C++. It is based on LLVM
    compiler infrastructure and is a plugin for Clang compiler.
  doc_url: https://github.com/vgvassilev/clad/blob/master/README.md
  dev_url: https://github.com/vgvassilev/clad/wiki

extra:
  recipe-maintainers:
    - vgvassilev
    - oshadura
