#!/bin/bash

set -x

# Check if shared object is in place.
test -f $PREFIX/lib/clad${SHLIB_EXT}

# Check installed compiler sanity.

clang --version
echo "" | clang -fsyntax-only -xc++ - -v
echo "#include <vector>" | clang -fsyntax-only -xc++ - -v

# Check if we can process a simple program.
clang -I$PREFIX/include -fplugin=$PREFIX/lib/clad${SHLIB_EXT} -osanity test.cpp
./sanity

# Run all tests we ran as part of the build but now with clad installed from a
# package.

LLVM_CONFIG=llvm-config

LLVM_VERSION=$(llvm-config --version)
LLVM_VERSION_MAJOR=${LLVM_VERSION%%.*}
LLVM_BIN_DIR=$(llvm-config --bindir)
LLVM_LIB_DIR=$(llvm-config --libdir)
LLVM_HOST_TARGET=$(llvm-config --host-target)
echo "
## Autogenerated LLVM/clad configuration. Do not edit!
import sys

config.clang_version_major = $LLVM_VERSION_MAJOR
config.llvm_tools_dir = \"$LLVM_BIN_DIR\"
config.llvm_libs_dir = \"$LLVM_LIB_DIR\"
config.llvm_lib_output_intdir = \"$LLVM_LIB_DIR\"
config.clad_obj_root = \"\"
config.target_triple = \"$LLVM_HOST_TARGET\"
config.shlibext = \"${SHLIB_EXT}\"
config.have_enzyme = \"\"

import lit.llvm
lit.llvm.initialize(lit_config, config)

# Let the main config do the real work.
lit_config.load_config(config, \"source/test/lit.cfg\")
" > lit.site.cfg

cat lit.site.cfg

# The unittests are dead now, don't try to discover and run them.
rm -fr source/test/Unit/

ln -s $PREFIX/libexec/llvm/FileCheck $PREFIX/bin/FileCheck

# Find back clang/Differentiator/Differentiator.h. Does not work because lit
# deletes the "possibly dangerous env variables".
# FIXME: We need a patch in clad.
#export CPLUS_INCLUDE_PATH="$PREFIX/include/"

#CLANG="clang" CLADLIB="$PREFIX/lib/clad${SHLIB_EXT}"  \
#lit --debug -sv --param clad_site_config=lit.site.cfg source/test


# Check jupyter
# python $RECIPE_DIR/jupyter_Clad_kernel_test.py  # [clangdev == "9.*" and not win]
